services:
  notifications:
    image: ghcr.io/elagala/ntfy-config/notifications:latest
    container_name: agala_notifications
    environment:
      - TZ=UTC
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_config:/etc/ntfy
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
    networks:
      - caddy_net

volumes:
  ntfy_cache:
  ntfy_config:

networks:
  caddy_net:
    external: true
